name: CI
on: [push]

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          bash ./bootstrap.sh
      - name: Build the library
        run: |
          cmake -DCMAKE_PREFIX_PATH=`pwd`/build/output -DCMAKE_LIBRARY_PATH=`pwd`/build/output/lib -DCMAKE_INSTALL_PREFIX=`pwd`/build/output .
          make
          make install